/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_ANOMALY_METADATA_H_
#define _EI_CLASSIFIER_ANOMALY_METADATA_H_

#include "edge-impulse-sdk/classifier/ei_model_types.h"

const uint16_t ei_classifier_anom_axes_939873_4[] = { 0, 6, 12 };

// (before - mean) / scale
const float ei_classifier_anom_scale_939873_4[3] = { 0.9113225728032042, 0.9100347685141845, 0.9081858285250204 };
const float ei_classifier_anom_mean_939873_4[3] = { 4.399408935043547, 4.418212978177601, 4.4056904338984575 };
const ei_classifier_anom_cluster_t ei_classifier_anom_clusters_939873_4[32] = {
	{ ( float[3] ) { 0.4681636691093445, 0.4682140052318573, 0.46181127429008484 }, 0.5625090806482549 },
	{ ( float[3] ) { 1.1865251064300537, 1.1927406787872314, 1.1794869899749756 }, 0.5139605048344416 },
	{ ( float[3] ) { 0.6122289896011353, 0.5949209928512573, 0.6099146008491516 }, 0.7094951668975593 },
	{ ( float[3] ) { 1.5267075300216675, 1.5360260009765625, 1.5337198972702026 }, 0.4377780243033201 },
	{ ( float[3] ) { -0.3527542054653168, -0.3100307285785675, -0.2437809556722641 }, 0.7013714792549467 },
	{ ( float[3] ) { 0.8997757434844971, 0.8968909978866577, 0.8798237442970276 }, 0.5691270724612184 },
	{ ( float[3] ) { 0.057751476764678955, 0.05240625888109207, 0.027329308912158012 }, 0.647547174118117 },
	{ ( float[3] ) { 2.0142602920532227, 2.004915952682495, 1.9932054281234741 }, 2.1969480317708587 },
	{ ( float[3] ) { -0.09904495626688004, -0.09667463600635529, -0.030123021453619003 }, 0.5766463898500341 },
	{ ( float[3] ) { -0.5954509377479553, -0.5213025212287903, -0.5014780759811401 }, 0.5751408198853942 },
	{ ( float[3] ) { -2.420682907104492, -2.428779125213623, -2.41286301612854 }, 0.7814078031227001 },
	{ ( float[3] ) { 0.3203790485858917, 0.31721198558807373, 0.3256587088108063 }, 0.7170542800344046 },
	{ ( float[3] ) { -0.15727828443050385, -0.1839931607246399, -0.24770566821098328 }, 0.6966039011312011 },
	{ ( float[3] ) { -1.1401697397232056, -1.1000689268112183, -1.1482235193252563 }, 0.6049412148047284 },
	{ ( float[3] ) { -1.2800995111465454, -1.2922874689102173, -1.277808427810669 }, 0.7152751535280317 },
	{ ( float[3] ) { 1.3609955310821533, 1.3621902465820312, 1.3668628931045532 }, 0.5416764658972829 },
	{ ( float[3] ) { 1.0310685634613037, 1.0366582870483398, 1.0386252403259277 }, 0.5990366381753245 },
	{ ( float[3] ) { 1.7234059572219849, 1.7326035499572754, 1.7357228994369507 }, 0.45188076164654534 },
	{ ( float[3] ) { -0.37086042761802673, -0.4394744634628296, -0.45991450548171997 }, 0.6954964593157501 },
	{ ( float[3] ) { -0.8874695301055908, -0.8435223698616028, -0.961829423904419 }, 0.728042562441443 },
	{ ( float[3] ) { -1.4763654470443726, -1.4382829666137695, -1.460310935974121 }, 0.683510058044154 },
	{ ( float[3] ) { 0.17909134924411774, 0.16871866583824158, 0.18486464023590088 }, 0.7348997413190468 },
	{ ( float[3] ) { -0.5863998532295227, -0.6458649039268494, -0.6913500428199768 }, 0.7565514554185357 },
	{ ( float[3] ) { -0.791939914226532, -0.7865674495697021, -0.7058689594268799 }, 0.7733691191368481 },
	{ ( float[3] ) { 0.7435243725776672, 0.7572637796401978, 0.7487403750419617 }, 0.7513776364935048 },
	{ ( float[3] ) { -2.7565555572509766, -2.7970879077911377, -2.784620523452759 }, 0.7988735593404953 },
	{ ( float[3] ) { -0.9985122680664062, -1.0439484119415283, -0.9221765398979187 }, 0.6202903404359875 },
	{ ( float[3] ) { -1.8642245531082153, -1.8669496774673462, -1.881370186805725 }, 0.6109596999482368 },
	{ ( float[3] ) { -2.120360851287842, -2.104689836502075, -2.0978567600250244 }, 0.5554112037344892 },
	{ ( float[3] ) { -1.6322332620620728, -1.6360673904418945, -1.6345025300979614 }, 0.6933380197224988 },
	{ ( float[3] ) { -3.4494690895080566, -3.493227243423462, -3.529510736465454 }, 1.472528531436674 },
	{ ( float[3] ) { 4.482333183288574, 4.6322479248046875, 4.659167766571045 }, 1.0523068240110411 },
};

#endif // _EI_CLASSIFIER_ANOMALY_METADATA_H_
