/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_MODEL_VARIABLES_H_
#define _EI_CLASSIFIER_MODEL_VARIABLES_H_

/**
 * @file
 *  Auto-generated complete impulse definitions. The ei_impulse_handle_t should
 *  be passed to ei_run_classifier() function to use this specific impulse.
 *  This file should only be included in ei_run_classifier.h file.
 */

#include <stdint.h>
#include "model_metadata.h"
#include "anomaly_metadata.h"
#include "tflite-model/tflite_learn_939873_3.h"
#include "tflite-model/tflite_anomaly_939873_6.h"
#include "edge-impulse-sdk/classifier/ei_model_types.h"
#include "edge-impulse-sdk/classifier/inferencing_engines/engines.h"
#include "edge-impulse-sdk/classifier/postprocessing/ei_postprocessing_common.h"

const char* ei_classifier_inferencing_categories_939873_1[] = { "fall_backward", "fall_bending", "fall_forward", "fall_hand", "fall_sideward_left", "fall_sideward_right", "fall_sitting", "fall_syncope", "walk" };

EI_CLASSIFIER_DSP_AXES_INDEX_TYPE ei_dsp_config_939873_2_axes[] = { 0, 1, 2 };
const uint32_t ei_dsp_config_939873_2_axes_size = 3;
ei_dsp_config_spectral_analysis_t ei_dsp_config_939873_2 = {
    2, // uint32_t blockId
    4, // int implementationVersion
    3, // int length of axes
    1.0f, // float scale-axes
    1, // int input-decimation-ratio
    "low", // select filter-type
    3.0f, // float filter-cutoff
    6, // int filter-order
    "FFT", // select analysis-type
    16, // int fft-length
    3, // int spectral-peaks-count
    0.1f, // float spectral-peaks-threshold
    "0.1, 0.5, 1.0, 2.0, 5.0", // string spectral-power-edges
    true, // boolean do-log
    true, // boolean do-fft-overlap
    1, // int wavelet-level
    "db4", // select wavelet
    false // boolean extra-low-freq
};

const float ei_dn_standard_scaler_mean_939873_2[18] = { 4.399408935043547, 0.06574135956254273, -0.8335678606440396, 2.272770159390237, 3.4495615348881756, 2.058546432389153, 4.418212978177601, 0.06590566280192965, -0.8527145518604327, 2.2769658624198703, 3.4645262518251676, 2.055558063494939, 4.405690433898456, 0.06761735259246897, -0.8415357719242406, 2.2751053152879077, 3.457651462601377, 2.05422059976006 };
const float ei_dn_standard_scaler_scale_939873_2[18] = { 1.0973062994851825, 1.999305841992508, 1.204149219110337, 5.41753149628539, 1.4842984864703963, 3.867558485383729, 1.0988591146168027, 2.0233895269428595, 1.2138080996562548, 5.499719171517554, 1.5079201530756734, 3.8639478719160483, 1.1010962388876906, 2.0120503246024795, 1.202139524044986, 5.415597643194194, 1.4830070552860362, 3.887816648311058 };
const float ei_dn_standard_scaler_var_939873_2[18] = { 0.8305088317006516, 0.2501736298915777, 0.6896669006113194, 0.03407195945194039, 0.4538972074381464, 0.06685381886119976, 0.8281632799046592, 0.24425361747826735, 0.6787345199188999, 0.033061227347767966, 0.4397879330524426, 0.06697881851720934, 0.8248014991336761, 0.24701442869152562, 0.6919747503896756, 0.03409629727494507, 0.45468807654860555, 0.06615892649699362 };
ei_data_normalization_standard_scaler_config_t ei_data_normalization_standard_scaler_config_939873_2 = {
    .mean_data = (float *)ei_dn_standard_scaler_mean_939873_2,
    .mean_data_len = 18,
    .scale_data = (float *)ei_dn_standard_scaler_scale_939873_2,
    .scale_data_len = 18,
    .var_data = (float *)ei_dn_standard_scaler_var_939873_2,
    .var_data_len = 18
};
ei_data_normalization_t ei_data_normalization_config_939873_2 = {
    (void *) &ei_data_normalization_standard_scaler_config_939873_2, // config
    DATA_NORMALIZATION_METHOD_STANDARD_SCALER, // method
    nullptr, // context
    nullptr, // init func
    nullptr, // deinit func
    &data_normalization_standard_scaler // exec func
};

const uint8_t ei_dsp_blocks_939873_1_size = 1;
ei_model_dsp_t ei_dsp_blocks_939873_1[ei_dsp_blocks_939873_1_size] = {
    { // DSP block 2
        2,
        18, // output size
        &extract_spectral_analysis_features, // DSP function pointer
        (void*)&ei_dsp_config_939873_2, // pointer to config struct
        ei_dsp_config_939873_2_axes, // array of offsets into the input stream, one for each axis
        ei_dsp_config_939873_2_axes_size, // number of axes
        1, // version
        nullptr, // factory function
        &ei_data_normalization_config_939873_2, // data normalization config
    }
};
const ei_config_tflite_graph_t ei_config_graph_939873_3 = {
    .implementation_version = 1,
    .model = tflite_learn_939873_3,
    .model_size = tflite_learn_939873_3_len,
    .arena_size = tflite_learn_939873_3_arena_size
};

const ei_config_tflite_graph_t ei_config_graph_939873_6 = {
    .implementation_version = 1,
    .model = tflite_anomaly_939873_6,
    .model_size = tflite_anomaly_939873_6_len,
    .arena_size = tflite_anomaly_939873_6_arena_size
};

const uint8_t ei_output_tensors_indices_939873_3[1] = { 0 };
const uint8_t ei_output_tensors_size_939873_3 = 1;
ei_learning_block_config_tflite_graph_t ei_learning_block_config_939873_3 = {
    .implementation_version = 1,
    .block_id = 3,
    .output_tensors_indices = ei_output_tensors_indices_939873_3,
    .output_tensors_size = ei_output_tensors_size_939873_3,
    .quantized = 0,
    .compiled = 0,
    .graph_config = (void*)&ei_config_graph_939873_3,
    .dequantize_output = 0,
};

ei_learning_block_config_anomaly_gmm_t ei_learning_block_config_939873_6 = {
    .implementation_version = 1,
    .block_id = 6,
    .anom_axis = ei_classifier_anom_axes_939873_6,
    .anom_axes_size = 3,
    .graph_config = (void*)&ei_config_graph_939873_6
};

const uint8_t ei_learning_blocks_939873_1_size = 2;
const uint32_t ei_learning_block_939873_3_inputs[1] = { 2 };
const uint8_t ei_learning_block_939873_3_inputs_size = 1;
const uint32_t ei_learning_block_939873_6_inputs[1] = { 2 };
const uint8_t ei_learning_block_939873_6_inputs_size = 1;
const ei_learning_block_t ei_learning_blocks_939873_1[ei_learning_blocks_939873_1_size] = {
    {
        3,
        &run_nn_inference,
        (void*)&ei_learning_block_config_939873_3,
        EI_CLASSIFIER_IMAGE_SCALING_NONE,
        ei_learning_block_939873_3_inputs,
        ei_learning_block_939873_3_inputs_size,
    },
    {
        6,
        &run_gmm_anomaly,
        (void*)&ei_learning_block_config_939873_6,
        EI_CLASSIFIER_IMAGE_SCALING_NONE,
        ei_learning_block_939873_6_inputs,
        ei_learning_block_939873_6_inputs_size,
    },
};

const size_t ei_postprocessing_blocks_939873_1_size = 2;
const ei_postprocessing_block_t ei_postprocessing_blocks_939873_1[ei_postprocessing_blocks_939873_1_size] = {
    {
        .block_id = 3,
        .type = EI_CLASSIFIER_MODE_CLASSIFICATION,
        .init_fn = NULL,
        .deinit_fn = NULL,
        .postprocess_fn = &process_classification_f32,
        .display_fn = NULL,
        .config = NULL,
        .input_block_id = 3
    },
    {
        .block_id = 6,
        .type = EI_CLASSIFIER_MODE_ANOMALY_GMM,
        .init_fn = NULL,
        .deinit_fn = NULL,
        .postprocess_fn = &process_anomaly,
        .display_fn = NULL,
        .config = NULL,
        .input_block_id = 6
    },
};

const uint8_t freeform_outputs_939873_1_size = 0;

uint32_t *freeform_outputs_939873_1 = nullptr;

const ei_impulse_t impulse_939873_1 = {
    .project_id = 939873,
    .project_owner = "Hectorgh24",
    .project_name = "Deteccion-caidas-9-clases",
    .impulse_id = 1,
    .impulse_name = "Impulse #1",
    .deploy_version = 2,

    .nn_input_frame_size = 18,
    .raw_sample_count = 100,
    .raw_samples_per_frame = 3,
    .dsp_input_frame_size = 100 * 3,
    .input_width = 0,
    .input_height = 0,
    .input_frames = 0,
    .interval_ms = 20,
    .frequency = 50,

    .dsp_blocks_size = ei_dsp_blocks_939873_1_size,
    .dsp_blocks = ei_dsp_blocks_939873_1,

    .learning_blocks_size = ei_learning_blocks_939873_1_size,
    .learning_blocks = ei_learning_blocks_939873_1,

    .postprocessing_blocks_size = ei_postprocessing_blocks_939873_1_size,
    .postprocessing_blocks = ei_postprocessing_blocks_939873_1,

    .output_tensors_size = 2,

    .inferencing_engine = EI_CLASSIFIER_TFLITE,

    .sensor = EI_CLASSIFIER_SENSOR_ACCELEROMETER,
    .fusion_string = "accX + accY + accZ",
    .slice_size = (100/4),
    .slices_per_model_window = 4,

    .has_anomaly = EI_ANOMALY_TYPE_GMM,
    .label_count = 9,
    .categories = ei_classifier_inferencing_categories_939873_1,
    .results_type = EI_CLASSIFIER_TYPE_CLASSIFICATION,
    .freeform_outputs_size = freeform_outputs_939873_1_size,
    .freeform_outputs = freeform_outputs_939873_1
};

ei_impulse_handle_t impulse_handle_939873_1 = ei_impulse_handle_t( &impulse_939873_1 );

ei_impulse_handle_t& ei_default_impulse = impulse_handle_939873_1;
constexpr auto& ei_classifier_inferencing_categories = ei_classifier_inferencing_categories_939873_1;
const auto ei_dsp_blocks_size = ei_dsp_blocks_939873_1_size;
ei_model_dsp_t *ei_dsp_blocks = ei_dsp_blocks_939873_1;
#endif // _EI_CLASSIFIER_MODEL_VARIABLES_H_
